[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
milestone_escrow = "6NikvvCPKpAkbdXWg8NtNes77mno854GjCouQqmkgyBS"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha 'programs/milestone_escrow/tests/*.ts'"

[hooks]
