spring.application.name=escrow

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/escrow_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=escrow_hackathon_super_secret_key_2024_must_be_at_least_256_bits_long
app.jwt.expiration=86400000

# File uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
app.upload.dir=uploads

# Server
server.port=8080

# Solana Configuration
solana.rpc.url=http://localhost:8899
solana.program.id=6NikvvCPKpAkbdXWg8NtNes77mno854GjCouQqmkgyBS
solana.wallet.private-key=
